### ISSUE TITLE
GitHub output for CITATION.cff with 'preferred-citation'

### ISSUE THREAD

**Issue by fgnievinski** [citation-file-format/ruby-cff#103]
When CITATION.cff has a 'preferred-citation', the DOI is absent in the output produced by GitHub.

Example: https://github.com/fgnievinski/mphw/blob/main/CITATION.cff

> A. R. Fagundes, M., Mendonça-Tinti, I., L. Iescheck, A., M. Akos, D., & Geremia-Nievinski, F. An open-source low-cost sensor for SNR-based GNSS reflectometry: design and long-term validation towards sea-level altimetry. GPS Solutions, 25(), 73

The publisher's "cite this article" text reads:

> Fagundes, M.A.R., Mendonça-Tinti, I., Iescheck, A.L. et al. An open-source low-cost sensor for SNR-based GNSS reflectometry: design and long-term validation towards sea-level altimetry. GPS Solut 25, 73 (2021). https://doi.org/10.1007/s10291-021-01087-1

Besides the major issue above (DOI missing), a related minor issue is the presentation of journal issue numbers: when it's absent, it should not produce empty parentheses "()" next to the volume number.

Related issues:
* https://github.com/citation-file-format/citation-file-format/issues/343
> * if I set "preferred citation", the BibTeX generated by GitHub does not seem to include most of the data entered
* https://github.com/ropensci/cffr/issues/7

**Comment by fgnievinski** [comment]
indeed, I wasn't aware it's possible to use doi without identifiers; now my example is fixed.

except for the journal issue number, please let me know if it should be split in a new ticket.

**Comment by jspaaks** [comment]
> except for the journal issue number, please let me know if it should be split in a new ticket.

Good with me either way, whatever @hainesr thinks is most convenient

**Comment by hainesr** [comment]
Let's just leave this issue open and I'll have a look at this as soon as possible.

**Comment by hainesr** [comment]
Right, I'm looking at this now. One thing I've also noticed in the comparison of the two outputs above is the apparent mangling of the authors' initials:
```
A. R. Fagundes, M.
```

Where you'd expect:
```
Fagundes, M.A.R.
```

It turns out that in the CFF file the middle initials have been specified in the `name-particle` field, which is for things like 'von' or 'van der' rather than initials. @fgnievinski, was this how the CFF was generated by `cffinit`? If so I think that's a bug in `cffinit`.

**Comment by hainesr** [comment]
Hi @arfon, with this and #105 now fixed it might be a good time for a bump of the version GitHub uses. Do you need me to cut a release?

**Comment by arfon** [comment]
:+1: will do. I'll look at getting this deployed early next week.

**Comment by fgnievinski** [comment]
> @fgnievinski, was this how the CFF was generated by `cffinit`? If so I think that's a bug in `cffinit`.

I've split this in a separate issue: 
https://github.com/citation-file-format/citation-file-format/issues/373
