### ISSUE TITLE
Add support for article in a conference contribution

### ISSUE THREAD

**Issue by 1kastner** [citation-file-format/ruby-cff#106]
I was told by the GitHub team (where I filed the issue first) that GitHub uses the code from this repository for creating the bibtex entry in the web UI (see Figure 1). Please bear with me as I have no Ruby skills and I could not easily create a PR for my issue.

![grafik](https://user-images.githubusercontent.com/5236165/155590393-8d1785c5-5773-474f-a0d1-0bf4b58aaaa4.png)
*Figure 1: Cite this repository*

I presented a software at a conference. Thus, I would like to have my conference contribution as the `preferred-citation`. My current draft (last information is still missing) is located at https://github.com/1kastner/conflowgen/blob/add-citation-hint/CITATION.cff for reference. When I pushed the changes, the produced bibtex output was this (I replaced the text, the issue comes with the keys):

```
@inproceedings{XXX,
address = {Bremen, DE},
author = {THE AUTHORS OF THE PAPER},
booktitle = {THE PROCEEDINGS NAME},
month = {2},
series = {MY CONFERENCE NAME},
title = {{MY TITLE}},
year = {2022}
}
```

When compared to the CITATION.cff, we can see that several of the keys went missing. Among others, the editors and the page range disappeared. I tried both `editors` and `editors-series` in case I misunderstood the documentation which is a bit vague at this place. But the first one seem to be the editors of a specific text, the second one the general editors of a conference proceeding.

Please tell me if I was mistaken while setting up the CFF file if that was the original cause. If a conference contribution is something you currently do not fully support, then it would be great if this feature could be added!

**Comment by 1kastner** [comment]
Btw, maybe an example for how to properly set up a conference article could be also part of the docs at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files?

**Comment by hainesr** [comment]
Hi @1kastner, Thanks for your issue.

At the moment we don't support the `editor` field in the `inproceedings` type, but we should so I'll add that as a new issue to sort that.

For a page range you should use `start` and `end` in CFF, not `pages` which is "number of pages" and BibTeX has no equivalent.

**Comment by 1kastner** [comment]
Thank you very much for your quick response, @hainesr. 

If instead of a specified page range (using `start` and `end`) I want to write `[in press]` as we can see it in the academic community from time to time, is there any canonical way of doing this in CFF?

**Comment by hainesr** [comment]
Ah ha, I see what you mean. Yes, this is a useful thing to be able to do.

CFF has a `status` field for a `reference` which is used for this. You can set it to `in-press`: [details here](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionsreferencestatus). If you use the `pages` field for this your CFF won't validate.

Now I need to add an issue to support `status` in the BibTeX and APA formats 😆

**Comment by 1kastner** [comment]
That would be awesome! As you have created your own issues based on this issue, how do you prefer it to be managed? Should I close this for now?

**Comment by hainesr** [comment]
Yes, let's close this one now.
