### ISSUE TITLE
BibTeX `inproceedings` type should support `editor` field.

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/ruby-cff#107]
As raised in #106.

**Comment by hainesr** [comment]
This is now implemented, and also for `proceedings` and `book` types too, as per the spec.

**Comment by 1kastner** [comment]
Thank you @hainesr !

**Comment by hainesr** [comment]
No problem at all 😄 

It might take a bit to surface in the GitHub UI though as there are some other changes to make as well.
