### ISSUE TITLE
Wrong comma `,` in the citation string

### ISSUE THREAD

**Issue by HannesWuensche** [citation-file-format/ruby-cff#116]
Dear CFF Team,

i added the CITATION.cff to one of my repositories: https://github.com/robert-koch-institut/COVID-SARI-Hospitalisierungsinzidenz 

Using the "Cite this Repository" button, I get the citation string:

```
Tolksdorf, K., Goerlitz, L., Haas, W., & Buda, S. (2022). COVID-SARI-Hospitalisierungsinzidenz [Data set]. https://doi.org/10.5281/zenodo.7234082
```

It seems to me, that the `,` in front of the `&` is wrong, since the `&` separates the last author. Right?

Beast Regards
@HannesWuensche

**Comment by HannesWuensche** [comment]
He @jspaaks,

thx for forwarding and the note on `licence`. I will change that. 

Best regards
Hannes

PS: Zenodo displays the same additional comma, probably they use `ruby-cff` too. I did send an bug report to them too (already some days ago).

**Comment by jspaaks** [comment]
I don't think Zenodo is using ruby-cff for their ingestion, I think they do their own ingestion (but maybe they try to mimic behavior for consistency). FWIW There's also something called an Oxford comma, e.g. https://en.wikipedia.org/wiki/Serial_comma that some people like to use.

**Comment by HannesWuensche** [comment]
Thanks for bringing the oxford comma up to my attention. I guess its an debate about style, so it can not be resolved in a logical manner.  Nerver the less Oxford says:

>Note that there is no comma between the penultimate item in a list and ‘and’/‘or’, unless required to prevent ambiguity – this is sometimes referred to as the ‘Oxford comma’. However, always insert a comma in this position if it  would help prevent confusion.

-- [Oxford Style Guide](https://www.ox.ac.uk/public-affairs/style-guide)

I personally don't see any ambiguity that would be resolved with the additional comma 😄

**Comment by hainesr** [comment]
Thanks for raising this @HannesWuensche. It is, as you say, a debate about style 😅 

All the [examples in the APA style guide](https://apastyle.apa.org/style-grammar-guidelines/references/examples/journal-article-references) use the comma before the '&', so I have replicated that behaviour.
