### ISSUE TITLE
Invalid APA formatting with no family names

### ISSUE THREAD

**Issue by Harmon758** [citation-file-format/ruby-cff#117]
The APA citation in the citation prompt on a GitHub repository's landing page seems to be invalid when only a given name is provided in the repository's CITATION.cff file, without a family name.

An example of this can be seen on https://github.com/tweepy/tweepy, where the APA citation in the citation prompt is:

> , H., Roesslein, J., & other contributors. Tweepy [Computer software]. https://doi.org/10.5281/zenodo.7259945

Since the author in [the repository's CITATION.cff file](https://github.com/tweepy/tweepy/blob/master/CITATION.cff) is listed as:
```
  - given-names: Harmon
    alias: Harmon758
    orcid: "https://orcid.org/0000-0002-2632-0921"
```
without a family-names key, the citation prompt seems to insert an empty string for the family name and start the APA citation with a comma followed by the initial for the given name.

I believe the given name should just be cited by itself instead, as a mononym, as [you should cite what you see, according to the APA Style](https://blog.apastyle.org/apastyle/2012/02/how-to-cite-pseudonyms.html).

I think the relevant code for this is:
https://github.com/citation-file-format/ruby-cff/blob/5a5b004ea88e5c2df026e6aed0df96add02fe419/lib/cff/formatters/apalike.rb#L134-L142

**Comment by hainesr** [comment]
Thanks for reporting this.

Do you think the BibTeX output is correct?

**Comment by hainesr** [comment]
I have fixed this to output
```
Harmon., Roesslein, J., & other contributors. Tweepy [Computer software]. https://doi.org/10.5281/zenodo.7259945
```
now.

Would you mind if I use your Tweepy CFF file as a test case?

**Comment by Harmon758** [comment]
> Do you think the BibTeX output is correct?

Yeah, it looks fine.

> I have fixed this to output
> 
> ```
> Harmon., Roesslein, J., & other contributors. Tweepy [Computer software]. https://doi.org/10.5281/zenodo.7259945
> ```
> 
> now.

Should the period be there? I think that's for when it's an initial, right?

> Would you mind if I use your Tweepy CFF file as a test case?

Not at all.

**Comment by hainesr** [comment]
> Should the period be there?

I'm not convinced it should! Have removed it now.

> > Would you mind if I use your Tweepy CFF file as a test case?

> Not at all.

Great, thanks 🚀

**Comment by hainesr** [comment]
I've pushed a patch release with this fix in it as there is at least one CFF file out there in the wild with this issue.

@arfon, should be a straight-forward bump from 1.0.0 to 1.0.1 for the GitHub interface.

**Comment by Harmon758** [comment]
Thanks for the quick fix and release!
