### ISSUE TITLE
The `message` value is not respected

### ISSUE THREAD

**Issue by zyrikby** [citation-file-format/ruby-cff#121]
According to the standard, one of the fields in the `cff` file is `message`. My understanding is that this message should be shown when you click on the "Cite this repository" dropdown button. However, respectively of its value, the message in the dropdown will be always: "If you use this software in your work, please cite it using the following metadata."

**Comment by hainesr** [comment]
I think this is a comment on the behaviour of the GitHub UI @arfon?

**Comment by arfon** [comment]
> I think this is a comment on the behaviour of the GitHub UI @arfon?

Yes, this is deliberate decision by the GitHub team. The GitHub UI does not support customisation of how the dropdown message is presented.

**Comment by zyrikby** [comment]
@arfon @hainesr what's the purpose of this message then in the standard? Is CFI used anywhere else?

**Comment by hainesr** [comment]
CFF is also used by Zotero. It's also designed to be human readable, so the message is for anyone who looks at the file, not just tooling.

I understand why GitHub doesn't use the message; it would be risky to put user defined text directly into the UI like that.
