### ISSUE TITLE
Escape special characters in BibTeX

### ISSUE THREAD

**Issue by jpthiele** [citation-file-format/ruby-cff#124]
In a recent addition of a preferred citation in a [PR](https://github.com/dealii/dealii/pull/16303),
we noticed that at least `&` is not properly escaped in BibTeX (i.e. `\&`). 
In the preferred citation this is part of the official journal title, 
so it will lead to a faulty BibTeX entry.
As far as I understand it, the code of this project is also used to produce the entries in 
'Cite this repository' on GitHub, right?
Otherwise we'd have to contact GitHub directly to fix this on here as well.

**Comment by hainesr** [comment]
Hello,

First, sorry for taking so long to get back to you!

Second, thanks for reporting this, and, good catch!

I'll have a look as soon as I can.

Rob

**Comment by hainesr** [comment]
I've released the fix for this and notified GitHub of the new Ruby CFF version.
