### ISSUE TITLE
What should be the minimum supported version of Ruby for this gem?

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/ruby-cff#27]
Currently 2.5, but should it be 2,6?

**Comment by arfon** [comment]
Yeah, I think it's reasonable to say 2.6, especially as 2.6 is going to be EOL'd soon: https://www.ruby-lang.org/en/downloads/

**Comment by hainesr** [comment]
Great, thanks - I'd lost track of which were EOL'd. I'm happy to stay just behind that.
