### ISSUE TITLE
Move to use the Licencee gem

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/ruby-cff#33]
In addition to what we use the spdx-licenses gem for now, this will provide discovery capabilities and align with GitHub's existing dependencies.

**Comment by hainesr** [comment]
On further inspection it seems that the Licensee gem doesn't provide a list of SPDX licences for us to compare when building the CFF.

**Comment by hainesr** [comment]
I think we can get round this if the licence can be validated as SPDX via the JSONSchema route (see citation-file-format/citation-file-format#208), but if we do it ourselves we will need to either use the spdx-licences gem or import the list directly.

Would appreciate thoughts @arfon.

**Comment by sdruskat** [comment]
See #208, this is covered by the new `schema.json`, albeit in a static way (auto-generated enum in schema file). If the new gem allows for dynamic validation, this could be an option as well, in case there are any new licenses added to the list that we won't cover for some time depending on how regularly we update the enum.

@jspaaks we cuold think about auto-updating the `license-enum` definition during CI?

**Comment by hainesr** [comment]
OK, this actually will work very nicely. We can pull out the list of SPDX licences from the schema and use that within the CFF gem - then we don't need the spdx-licenses gem or the licensee gem.

Also, now I've looked at it, I see that you've got the list of ISO 3166-1 alpha-2 codes in there too, so we can use them too. Are you going to put in the list of three letter language strings? 😄

**Comment by hainesr** [comment]
I think I'll close this one for now. When we get to adding features to extract data to build a CFF from a repo directly, I think we will need Licencee, but not yet.
