### ISSUE TITLE
Adapt ground truth to actual ground truth

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/ruby-cff#35]
Hi @hainesr, when preparing the new schema, we found that three of your CFF examples for testing Ruby CFF are actually invalid CFF, see https://github.com/citation-file-format/citation-file-format/pull/214#issuecomment-865053441.

(In short: `version` doesn't accept floats, `date`s don't accept full ISO dates, but only `date` objects formatted as `YYY-MM-DD`, even under older schemas.)

**Comment by hainesr** [comment]
Thanks. Must have crept in with the recent formatting extensions. Will investigate!
