### ISSUE TITLE
Consider autogenerating Bibtex keys

### ISSUE THREAD

**Issue by merrygoat** [citation-file-format/ruby-cff#37]
At the moment the Bibtex generator generates the citation with the default BibTeX key `YourReferenceHere`: 

https://github.com/citation-file-format/ruby-cff/blob/db84460fd8a0f4d3c9e3c9d7a8b3bf134ba3c2bd/lib/cff/formatter/bibtex_formatter.rb#L34

Some reference managers like [jabref](https://www.jabref.org/) and [Zotero](https://www.zotero.org/) auto generate the BibTeX key according to a standard format. This is convienient as I don't care that much what they key is, just that it is unique.

I like Jabrefs default which is the terse format [[author][year]](https://docs.jabref.org/setup/citationkeypatterns) to give Haines2021. There is however a risk of key overlap with this format. I dont use Zotero but I think they use [author]\_[firstwordoftitle]\_[year] which would give Haines_ruby-cff_2021.

**Comment by hainesr** [comment]
I think this is a good idea Peter, thanks.

I've had a look at how we might do this as easily as possible, and I think that all we need is in the `values` hash in the formatter itself. This would mean we don't need to parse the model a second time.

The one tricky bit would be parsing a last name from the first author in the `author` field as it is currently formatted. It currently looks like `First Author and Second Person and ...` and given that a last name could also include "von", "de la", etc we'd potentially get ourselves into a muddle fairly quickly. However it is allowed to format the `author` field as `Author, First and Person, Second and ...` [1] so if we used this format then we could use everything before the first `,` for the `reference` field.

I'll work up a PR.

[1] https://tex.stackexchange.com/questions/557/how-should-i-type-author-names-in-a-bib-file
