### ISSUE TITLE
Add a CONTRIBUTING.md?

### ISSUE THREAD

**Issue by arfon** [citation-file-format/ruby-cff#47]
What do you think about adding a `CONTRIBUTING.md` file to this repository? This is especially important for potential new contributors who might want to understand how the project works, who is working on it, how best to contribute etc. The Mozilla guide has some good ideas about what to include: https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by hainesr** [comment]
I think a good idea, and nice to get it in for version 1.0 of the gem. Would you mind working something up @arfon?

**Comment by hainesr** [comment]
Done!
