### ISSUE TITLE
Any chance of having a paper being the reference to cite?

### ISSUE THREAD

**Issue by jgbarah** [citation-file-format/ruby-cff#54]
I have a use case where we would like a paper in a journal to be the reference to cite. I've tried including it under the `references` key (which seems to be the right way, according to the cff specification), but it seems to be ignored (at least when producing BibTeX). Also, I've tried including the data as keys in the top level, but the `type` key seems to be ignored, which renders a `@misc` BibTeX label (and probably it should be ignored, according to the specification).

Is there any way to write the cff file so that a proper reference for the paper journal is produced?

**Comment by hainesr** [comment]
I think this is possibly a more fundamental question about CFF itself, rather than the Ruby library. Do you think @sdruskat, @jspaaks?

**Comment by jgbarah** [comment]
Apparently CFF allows for using `references` exactly for this (see [References](https://github.com/citation-file-format/citation-file-format/blob/main/README.md#references-optional) and [Reference Keys](https://github.com/citation-file-format/citation-file-format/blob/main/README.md#reference-keys)), but it seems those keys cannot be at the top level, but specifically below a `references` key.

**Comment by hainesr** [comment]
The issue would be which reference to choose. But it seems this is coming via a `preferred-citation` field in the next version of CFF: https://twitter.com/stdruskat/status/1420366493439700994?s=20

**Comment by jspaaks** [comment]
@jgbarah yep `preferred-citation` from the upcoming CFF schema release v1.2.0 is supposed to do exactly that. I don't think ruby-cff supports this yet, but perhaps it will

**Comment by hainesr** [comment]
It will, but I had no idea it was on the way! 🤣

Please can you point me at the docs for it?

**Comment by jspaaks** [comment]
Bit of a WIP, but here you go https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#credit-redirection

**Comment by hainesr** [comment]
Ah ha, thanks @jspaaks! I hadn't spotted that documentation 😄

I'll close this issue and open a new feature for adding `preferred-citation`...

**Comment by jgbarah** [comment]
I think `preferred-citation` is nice, but when you export the contents of the CFF file in other formats, you can by default export all references, no need of `preferred-citation`. I'm not reopening, anyway, because this could be a new feature request: support for `references`... Should I open a new issue with that?
