### ISSUE TITLE
Add `preferred-citation` field to the top-level.

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/ruby-cff#55]
As discussed in #54.

**Comment by hainesr** [comment]
So. `preferred-citation` is now in ruby-cff.

Next question is how to surface it in the BibTeX/APA outputs. If there is a `preferred-citation`, should that be the one that is output, over the top-level data? It feels like this is the expectation when providing a `preferred-citation` but would appreciate thoughts from @sdruskat, @jspaaks and indeed others!

**Comment by sdruskat** [comment]
Great!

I think that what GitHub want (correct me if I'm wrong, @arfon) is indeed to use the `preferred-citation` whenever there is one, so as to respect the users' preferences (although this goes against the principles somewhat :wink:).

**Comment by hainesr** [comment]
You know what? I'll make it configurable, then everyone has options! 🚀

**Comment by jspaaks** [comment]
> You know what? I'll make it configurable, then everyone has options! rocket

But wait isnt the fact that the user added a `preferred-citation` already the configuration?

**Comment by sdruskat** [comment]
I thought that making it configurable would be the best option as well, but didn't want to put the burden on Rob. I *do* think that having this configurable is good, because then, other users of the Gem (or GitHub in the future!) could choose to either follow the user, or follow best practice (see the principles paper, "always cite the software") or just display both :slightly_smiling_face:.

**Comment by hainesr** [comment]
I can make it configurable with a default.

What should the default be? Use `preferred-citation` (for the reasons @jspaaks mentions above)?

**Comment by sdruskat** [comment]
Best option for now, defo!

**Comment by arfon** [comment]
> What should the default be? Use `preferred-citation` (for the reasons @jspaaks mentions above)?

This makes sense to me. I've been thinking of `preferred-citation` as an _override_ for any other behavior so I think if it exists, this is what GitHub should use in the UI.

**Comment by hainesr** [comment]
I have pushed this to `main` now, with the following features:

- When outputting a citation string, honouring `preferred-citation` is the default, if present, but can be turned off.
- The BibTeX formatter respects the type of reference being generated and tries to use a sensible corresponding BibTeX type e.g. `@misc` for software and `@book`, `@article`, `@inproceedings` etc as appropriate.
- The APA formatter only adds '[Computer software]' if it is indeed software being referenced.
- The formatters expect validated CFF files as input. I felt that this was better than validating within the formatter so that for e.g. GitHub things aren't being validated multiple times when outputting multiple formats at once.

Happy to have thoughts on these changes and issues raised where I've missed something.

**Comment by arfon** [comment]
⚡ thanks @hainesr. I've taken these changes for a spin and have found a few issues with some of the outputs for articles. I've opened a PR to demonstrate the issues here: https://github.com/citation-file-format/ruby-cff/pull/71

**Comment by hainesr** [comment]
Thanks @arfon. I'll look at your PR in detail tomorrow. For reference I used the fixtures that @mfenner provided in #67 for the APA format.

**Comment by arfon** [comment]
> Thanks @arfon. I'll look at your PR in detail tomorrow. For reference I used the fixtures that @mfenner provided in #67 for the APA format.

:+1: thanks @hainesr :bow:. From what I can see in #67, the examples are almost (all?) software citations, not articles (i.e., `preferred-citation` entities).

Ultimately it will be great to switch to CSL for formatting these outputs :-)

**Comment by hainesr** [comment]
Hi @arfon, yes now I've had chance to look at your PR properly I see the difference!

Thanks, we do need more test coverage in this area and we're missing some of the useful article level data in the citations at the moment. I'll try and look at this today.
