### ISSUE TITLE
Error with seemingly valid YAML file

### ISSUE THREAD

**Issue by larsgw** [citation-file-format/ruby-cff#57]
I am getting an error on a `CITATION.cff` file that seems to be correct YAML 1.2 as it passes http://www.yamllint.com/, and since the file was formatted with a library ([js-yaml](https://www.npmjs.com/package/js-yaml)) and not by hand. I do not see any incorrect properties either. However, GitHub tells me the file cannot be parsed. I cannot get gem or bundler to work locally unfortunately, so I do not know how I can test this myself. Is there any way I can find out what is going wrong?

**Comment by larsgw** [comment]
Some possible problems I found along the way, feel free to add:

  - Missing `date-released` or `version`. Can be easy to miss if you import the data from a different source.
  - As mentioned above, having dates with timestamps (`2021-07-29T00:00:00.000Z` instead of `2021-07-29`). The default behavior of e.g. [js-yaml](https://www.npmjs.com/package/js-yaml).

**Comment by hainesr** [comment]
Please could you paste or link to your `CITATION.cff` file?

Certainly I think that `version` is required according to [the CFF spec](https://github.com/citation-file-format/citation-file-format/tree/1.2.0#software-citation-metadata-required).

**Comment by sdruskat** [comment]
> I am getting an error on a `CITATION.cff` file that seems to be correct YAML 1.2 as it passes http://www.yamllint.com/, and since the file was formatted with a library ([js-yaml](https://www.npmjs.com/package/js-yaml)) and not by hand. I do not see any incorrect properties either.

Without having seem the CFF file, it sounds a lot like an issue with missing required fields (which is something that sets CFF apart from vanilla YAML). The number of required fields will also be smaller in 1.2.0 than it currently is in 1.1.0.

**Comment by larsgw** [comment]
It was the timestamp thing ([file](https://github.com/citation-js/citation-js/blob/main/CITATION.cff)). Sorry, I had said I fixed it in an earlier version of my reply but I edited it out for some reason.

**Comment by larsgw** [comment]
(and since the timestamp was the only problem, https://citation-js.github.io/cff-generator now works)

**Comment by sdruskat** [comment]
> (and since the timestamp was the only problem, https://citation-js.github.io/cff-generator now works)

Nice one!
