### ISSUE TITLE
Should validating a file fail if it is *not* named `CITATION.cff`?

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/ruby-cff#62]
I think a question for @sdruskat, @jspaaks, @arfon and others(?)

The CFF spec says that the CFF file should be named `CITATION.cff`. The ruby-cff gem has two levels of validation:
1. validating the internal model/data structure;
2. validating a CFF file directly.

The first case is useful for validating a structure that you are building programmatically; the second is for validating an existing file. So, should the second case fail if the file that is being validated is not `CITATION.cff`?

**Comment by arfon** [comment]
I think there's value in requiring a standard name (i.e., validation should fail if the name isn't CITATION.cff)

**Comment by hainesr** [comment]
I'll implement this, but I'll leave it until after the `0.8` release.
