### ISSUE TITLE
Errors in APA formatting

### ISSUE THREAD

**Issue by mfenner** [citation-file-format/ruby-cff#66]
The formatted citations in APA style generated by the gem have the following errors (when comparing to the APA citations generated by `citeproc-ruby`:

* Author names should have a comma before the initials for first names, and an ampersand before the last author: `Boonstra, S., &amp; Hofmeyer, H.` instead of `Boonstra S., Hofmeyer H.`.
* It should be `https://doi.org/10.5281/zenodo.3823893"` instead of `DOI: https://doi.org/10.5281/zenodo.3823893`.
* Don't show a URL if a DOI (expressed as URL) is shown: `https://doi.org/10.5281/zenodo.596912` instead of `DOI: https://doi.org/10.5281/zenodo.596912 URL: https://github.com/bjmorgan/bsym`
* The software title should be in italics in APA 7th edition: `<i>My Research Software</i> (Version 2.0.4).` instead of `My Research Software (version 2.0.4).`.
* The citation should include a label [computer software]: `<i>HaploWinder</i> (Version 1.11) [Computer software].` instead of `HaploWinder (version 1.11).`.

**Comment by hainesr** [comment]
Can these issues be fixed (i.e. the APA formatter replaced) by the PR resulting from #64?

**Comment by mfenner** [comment]
Yes. I assume that I can trust CSL and `citeproc-ruby`, in particular since the styles are regularly updated.

One topic for discussion would be whether to generate the formatted citation in HTML or plain text. I am currently doing the latter to show italics, bold, superscript, etc. and assume this is rendered in the GitHub UI, i.e. as HTML.

**Comment by hainesr** [comment]
I have pushed fixes for all of the above, except the italics, because we won't be able to merge the `citeproc-ruby` stuff into `ruby-cff` in time for the next version to go into GitHub. I thought it best to fix what I could for now and the `citeproc-ruby` can go in once we've polished it and had the relevant discussions with the GitHub folks.
