### ISSUE TITLE
How can I customize the BibTeX output of ruby-cff to match an existing BibTeX file?

### ISSUE THREAD

**Issue by cpitclaudel** [citation-file-format/ruby-cff#72]
I'd like to use the new CITATION.cff file format on Github.  In addition to citing the software itself, though, I'd like people to cite the accompanying paper.  I understand I can do this with the `references` field.

Since most people in my field will be using BibTeX feature, I need control over that.  Is there a way to specify what the BibTeX should look like?

Things that I worry about are missing fields (`booktitle`, `series`, `isbn`, `location`, etc.) and support for capitalization (BibTeX supports `{}` to indicates parts of a title whose capitalization shouldn't change, and I'm not sure how to do this in CITATION.cff)

Here's an example of a BibTeX file that I'd love to convert to CITATION.cff: https://github.com/cpitclaudel/alectryon/blob/master/CITATION.bib . 

Thanks!

**Comment by ddsjoberg** [comment]
I am interested in this too. I see that today's release included a `preferred-citation` entry, and I think this is how we're meant to customize the results. But I didn't see an example or instructions on how to specify the desired output. Are we meant to provide desired outputs for each type, e.g. bibtex output, APA, etc.? Thank you!

From the README
````
#### Citing a paper rather than software

The CFF has been designed with direct citation of software in mind.
We'd like software to be considered a first-class research output, like journal articles and conference papers. 
If you would rather that your citation text points to a paper that describes your software, rather than the software itself, you can use the `preferred-citation` field for that paper. 
When producing citation text this library will honour `preferred-citation`, if present, by default. 
If you would like to specify a `preferred-citation` and still produce a direct citation to the software then you can configure the formatter as follows:

```ruby
cff = CFF::File.read('CITATION.cff')

cff.to_bibtex(preferred_citation: false)
cff.to_apalike(preferred_citation: false)

```
````

**Comment by cpitclaudel** [comment]
@ddsjoberg Even with preferred-citation I don't think you can: AFAICT the BibTeX will still be auto-generated, and hence won't have the right info in it.

**Comment by hainesr** [comment]
Hi @cpitclaudel and @ddsjoberg.

`preferred-citation` is indeed the mechanism in CFF to override the default software citation with a reference to something else. At present we try to add as much info as possible to the BibTeX but we might not have it all mapped yet. I note that in the `CITATION.bib` file above there are a few fields specified which are not part of core BibTeX (https://mirror.ox.ac.uk/sites/ctan.org/info/bibtex/tamethebeast/ttb_en.pdf) - are they BibLaTeX fields? We are considering more output formats at the moment.

Also, I believe that GitHub are considering pulling citation data from other files in the future.

**Comment by ddsjoberg** [comment]
Thank you @hainesr !

To use this feature, is this how we specify it?

````
cff-version: 1.2.0
message: If you use ruby-cff in your work, please cite it using the following metadata
title: Ruby CFF Library
preferred-citation: true
...
```

Then the resulting bibtex file will include the fields needed to cite a published paper? (sorry, if I am being dense here)

**Comment by hainesr** [comment]
Hi @ddsjoberg, you're not being dense at all!

`preferred-citation` is a reference object, so specify it the same way you do one of the references in the `references` field. There is an example here: https://github.com/citation-file-format/ruby-cff/blob/main/test/files/tidyverse-joss-paper.cff

**Comment by cpitclaudel** [comment]
> are they BibLaTeX fields? We are considering more output formats at the moment.

I'm not entirely sure — it's the default that ACM produces (see https://dl.acm.org/doi/10.1145/3426425.3426940)

Thanks for your work!

**Comment by ddsjoberg** [comment]
> Hi @ddsjoberg, you're not being dense at all!
> 
> `preferred-citation` is a reference object, so specify it the same way you do one of the references in the `references` field. There is an example here: https://github.com/citation-file-format/ruby-cff/blob/main/test/files/tidyverse-joss-paper.cff

Thank you for the example! Very helpful!

**Comment by sdruskat** [comment]
CFF version 1.2.0 was released yesterday, and there's another [example in the new schema guide](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#credit-redirection) as well.

**Comment by arfon** [comment]
Note there's an example related to this in the GitHub Docs too: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files#citing-something-other-than-software

Closing this for now, but please comment if there's more to do here.
