### ISSUE TITLE
Citation prompt spins on this CFF file

### ISSUE THREAD

**Issue by arfon** [citation-file-format/ruby-cff#74]
Not sure what is going on here but this project's CFF file doesn't work...

https://github.com/WhoIsJack/data-driven-analysis-lateralline

**Comment by hainesr** [comment]
Hi @arfon

This validates fine for me (but note that the API changed for validation due to #62 - this shouldn't be the issue as the file is called 'CITATION.cff').

I think the issue is in `to_apalike` - debugging this now...

**Comment by hainesr** [comment]
Yes, I'm an idiot - one condition not caught when a `preferred-citation` doesn't have a `volume` for the APA-like formatter.

I will push the fix tonight.

**Comment by hainesr** [comment]
I've pushed the fix for this particular issue in `ruby-cff` - was an easy fix and is also now covered by tests...

**Comment by arfon** [comment]
OK this is now live on GitHub.

**Comment by hainesr** [comment]
Hooray, the fix worked! 🎉 

That was fast work by the GitHub team - thanks @arfon!

**Comment by hainesr** [comment]
Also, I realise that GitHub don't need me to do it, but I think this warrants cutting a `0.9.0` gem. I'll do that in the next couple of days...
