### ISSUE TITLE
Parsing data from another file type or using CrossRef

### ISSUE THREAD

**Issue by FedericoTartarini** [citation-file-format/ruby-cff#76]
Thank you very much for adding this new feature. It is great. 

However, It would be fantastic if you could add a feature that parses the data from another file type and automatically creates a `.cff` file. For example, it would be great if I could upload a BibTex file and GitHub would convert it automatically in a `cff` file. BibTeX file are more common than `.cff`.

Another great feature would be if you could add a search bar, where, I can search for my paper on [CrossRef](https://search.crossref.org) and the GitHub parses all the necessary info from their website.

**Comment by arfon** [comment]
Thanks for the feedback @FedericoTartarini! Conversion should probably be accomplished by something like this library https://github.com/datacite/bolognese - I'm not sure if this supports CFF yet but I'm sure it could be added.

As for some kind of deeper integration of GitHub with CrossRef – I understand the potential value here but I don't see GitHub doing anything like that sorry – it's way too of a niche use case for such a feature to exist on GitHub.

**Comment by hainesr** [comment]
I think @mfenner and I will talk about bolognese/cff integration at some point soon.

**Comment by mfenner** [comment]
@hainesr https://github.com/datacite/bolognese is a pretty complex library (as it supports a number of metadata formats). I think that a GitHub Action that converts to/from CFF and using bolognese could work well.

Adding CFF support to bolognese should be straightforward, and we should add **readers** and **writers** (to/from a core metadata format that is basically DataCite JSON).

What are the initial use case(s) that need addressing?
