### ISSUE TITLE
APA style still marks datasets as software

### ISSUE THREAD

**Issue by rettinghaus** [citation-file-format/ruby-cff#81]
Although the `CITATION.cff` carries a `type: dataset` in the APA style citation on GitHub still _[Computer software]_ is shown.

**Comment by hainesr** [comment]
Thanks for spotting this @rettinghaus. I haven't implemented `type` at the top-level yet - only for references. I'll get that sorted ASAP.

**Comment by arfon** [comment]
This should be fixed on GitHub now with the updated gem.

**Comment by rettinghaus** [comment]
Looks great, thanks!
