### ISSUE TITLE
Visual support for multiple references

### ISSUE THREAD

**Issue by BramVanroy** [citation-file-format/ruby-cff#82]
Hello

In my experience, in academia you may provide an open-source implementation as a single library even though that it is work that has been published incrementally. For instance, I have two repositories which both have CITATION files that contain two bibtex entries ([example](https://github.com/BramVanroy/astred)). Currently Github does detect the CITATION file, but it does not display the information. Instead it links through to the CITATION file - probably because it cannot be parsed as a single reference. 

My request is for the Github implementation to be able to handle multiple given references, visually within clicking through to the whole CITATION file. There is definitely enough space in the UI to display at least two references (as the "citation" box is a pop up), but I am not sure if that would require anything different in terms of the format of the CITATION file.

Thanks

**Comment by hainesr** [comment]
I think that as this is a UI question, then it's one for GitHub folks @arfon?

I suspect some level of support would be required from `ruby-cff`, but I'll hold off thinking about that unless GitHub wants to make such a change to their UI.

**Comment by sdruskat** [comment]
The example is a plain text `CITATION` file, not formatted in the Citation File Format. I suspect that this is actually out of scope for any repo in this org, but perhaps Arfon can forward this.

**Comment by arfon** [comment]
> My request is for the Github implementation to be able to handle multiple given references, visually within clicking through to the whole CITATION file. There is definitely enough space in the UI to display at least two references (as the "citation" box is a pop up), but I am not sure if that would require anything different in terms of the format of the CITATION file.

While I think there could possibly be space for a second reference, what about a third, fourth etc? I currently don't see a good way to handle this sort of situation other than detecting the `CITATION` file and linking to it in the UI with instructions for humans (this is the current behaviour).

Not sure how you're maintaining issues on this repo @sdruskat (i.e., whether you want to keep this open as a possible enhancement) but just to be clear, I think the current implementation supports a range of use cases.

**Comment by hainesr** [comment]
I think this is a GitHub UI question, not a ruby-cff question, so I'm going to close this.
