### ISSUE TITLE
Update mappings of `preferred-citation` types for BibTeX output

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/ruby-cff#83]
Example: dieghernan/cffr#7

**Comment by dieghernan** [comment]
Thanks @hainesr , I just join the issue to keep track of it. Regards

**Comment by hainesr** [comment]
@dieghernan, please may I use the CFF in your test repo as a test case in ruby-cff?

**Comment by dieghernan** [comment]
Sure!

**Comment by hainesr** [comment]
I have now merged support for `booklet`, `manual`, `techreport` and `unpublished` BibTeX types. @arfon has added the `proceedings` BibTeX type.

**Comment by arfon** [comment]
...and this is now live on GitHub. Any issues, let me know!
