### ISSUE TITLE
Preferred citation supported types

### ISSUE THREAD

**Issue by arfon** [citation-file-format/ruby-cff#90]
We have a [handy new table in the GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#citing-something-other-than-software) to help GitHub users understand which outputs are supported as the `preferred-citation` option.

<img width="751" alt="Screenshot 2021-10-06 at 14 42 52" src="https://user-images.githubusercontent.com/4483/136214418-8e1565c6-6b02-4cc9-b320-9f21619d8e0b.png">

I *think* the list is (from [this list](https://github.com/citation-file-format/ruby-cff/blob/ac96f56cb71652544752419050f8e42d37873917/lib/cff/formatter/bibtex_formatter.rb#L24-L35)):

|  Resource |  CFF Type | BibTeX output type |
|---|---|---|
| Research article/paper  |  `article` | `@article` |
| Book  | `book`  | `@book` |
| Booklet  | `booklet`  | `@booklet` |
| Conference article/paper  | `inproceedings`  | `@inproceedings`|
|  Conference proceedings | `proceedings`  | `@proceedings` |
|  Manual | `manual`  | `@manual` |
| Misc | `misc` | `@misc`
| Software | `software` | `@software` |
| Tech report | `techreport` | `@techreport` |
| Unpublished | `unpublished` | `@unpublished` |

Is this correct @hainesr? The only issue I see here is that `booklet` currently produces a `@misc` BibTeX output which I believe is incorrect?

**Comment by hainesr** [comment]
Hi @arfon,

It's not quite as simple a mapping as that. If you expand that code you effectively get this:

| Resource | CFF Type [1] | BibTex output type |
|-----------|-----------|-----------------------|
| Journal article/paper | `article` | `@article` |
| Book | `book` | `@book` |
| Booklet (bound but not published) | `pamphlet` | `@booklet` |
| Conference article/paper | `conference-paper` | `@inproceedings` |
| Conference proceedings | `conference`, `proceedings` | `@proceedings` |
| Magazine article | `magazine-article` | `@article` |
| Manual | `manual` | `@manual` |
| Misc/generic/other | `generic`, any other CFF type | `@misc` | 
| Newspaper article | `newspaper-article` | `@article` |
| Software |  `software`, `software-code`, `software-container`, `software-executable`, `software-virtual-machine` | `@software` |
| Report/technical report | `report` | `@techreport` |
| Unpublished | `unpublished` | `@unpublished` |

[1] https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionsreferencetype
