### ISSUE TITLE
When formatting, parse dates from `date-start` and `date-end` if appropriate.

### ISSUE THREAD

**Issue by hainesr** [citation-file-format/ruby-cff#92]
Feels like we need a heuristic about when to use `year`/`month` or `date-start`/`date-end`. Will think on this.

From https://github.com/citation-file-format/ruby-cff/issues/79#issuecomment-937210223.

**Comment by hainesr** [comment]
Right, `date-start`/`date-end` fields are only on CFF Entities with the intention of using them (primarily, I think) for conferences. So I think we're OK to just look for them on conference related `preferred-citation`s.

Does that make sense from a CFF perspective @sdruskat and @jspaaks?

And does that make sense from a user perspective @arfon and @tgamblin?

**Comment by tgamblin** [comment]
Makes sense to me!
