### ISSUE TITLE
GitHub: illegal bibtex key, non-ascii character

### ISSUE THREAD

**Issue by nschloe** [citation-file-format/ruby-cff#96]
When creating a BibTeX citation for any of my software, GitHub will chose the BibTeX key to be `{lastname_title}`, in my case resulting in, e.g.,
```
Schlömer_pygmsh_A_Python
```
This isn't a legal BibTeX key because of the `ö`, and should probably be replaced by `oe`.

**Comment by arfon** [comment]
I *think* we just used `String#encode` (e.g., https://stackoverflow.com/questions/1268289/how-to-get-rid-of-non-ascii-characters-in-ruby) but I'm trying to get a definitive answer here.

**Comment by hainesr** [comment]
Yeah, I saw that one but it's still quite a lot of work to do "nice" transliteration. Rails adds the [`String#parameterize`](https://api.rubyonrails.org/classes/String.html#method-i-parameterize) method (actually [`ActiveSupport::Inflector.parameterize`](https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-parameterize)) which would be perfect, but we can't pull Rails in just for this!

I was wondering about adding a "good enough" `parameterize`-type method based on that SO post you mention but using `String#parameterize` if available?

Certainly it seems we need to avoid UTF8 in BibTeX citekeys: https://tex.stackexchange.com/questions/359215/utf8-character-in-citation-keys

**Comment by arfon** [comment]
> but we can't pull Rails in just for this!

Could we use the Rails/ActiveSupport method if they're available, and have some kind of fall-back for the Gem outside of a Rails-enabled context. 

Not sure I've ever seen anything like this done before (or if it's a good idea) but just wanted to mention it incase :-)

**Comment by hainesr** [comment]
> Could we use the Rails/ActiveSupport method if they're available, and have some kind of fall-back for the Gem outside of a Rails-enabled context.

That's what I meant in my badly worded comment 😆 

I'll look into it...
