### ISSUE TITLE
URI.open is not safe

### ISSUE THREAD

**Issue by dorianmariefr** [citation-file-format/ruby-cff#98]
Seen in the README, see brakeman warning

**Comment by hainesr** [comment]
Thanks for raising this.

I'm not overly worried about this use of `URI.open` as it's purely used as an example in the README, and in particular it's being used with a static string passed into it. There are no arbitrary parameters being injected.

So I'm going to leave it, but I will add a note to the README to use something a little more robust in 'real' code.
